#! /bin/bash
powerlog="/home/pi/ARPiE/Logs/pwr1.log"
if [[ ! -e $powerlog ]]; then
	touch $powerlog
fi
while :
do
	sleep 120
	if [[ $(sudo mopicli -v1) = "Source #1 voltage: 0" ]]; then
		sudo mopicli -won 21600
		echo "Date:"$( date )" - "$( sudo mopicli -v1 ) >> "$powerlog"
		echo "Date:"$( date )" - Going to sleep for 6 hours now" >> "$powerlog"
		sudo mopicli -wsd 10
		exit 0
	else
		echo "Date:"$( date )" - "$( sudo mopicli -v1 ) >> "$powerlog"
	fi
done
